# Generated by Django 6.0.5 on 2026-05-26 18:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_entrada', models.DateTimeField(verbose_name='Data e hora da entrada')),
                ('data_hora_saida', models.DateTimeField(verbose_name='Data e hora da saída')),
                ('tamanho_estoque', models.IntegerField(verbose_name='Tamanho do estoque')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('validade', models.DateField(verbose_name='Validade')),
                ('localizacao', models.CharField(max_length=45, verbose_name='Localização')),
                ('lote', models.CharField(max_length=45, verbose_name='Lote')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.FloatField(verbose_name='Valor pago')),
                ('forma_de_pagamento', models.CharField(max_length=15, verbose_name='Forma de pagamento')),
                ('troco', models.FloatField(verbose_name='Troco')),
                ('data_hora_pagamento', models.DateTimeField(verbose_name='Data e hora do pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('turno', models.CharField(max_length=50, verbose_name='Turno')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=45, verbose_name='Categoria')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('disponibilidade', models.CharField(max_length=45, verbose_name='Disponibilidade')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estoque')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_pedido', models.DateTimeField(verbose_name='Data e hora do pedido')),
                ('valor_total', models.FloatField(verbose_name='Valor total')),
                ('observacoes', models.CharField(max_length=200, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pagamento')),
                ('produtos', models.ManyToManyField(to='core.produto')),
            ],
        ),
    ]
