# Generated by Django 6.0.6 on 2026-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Lanche', 'Lanche'), ('bebida', 'Bebida')], max_length=45, verbose_name='Categoria'),
        ),
    ]
