# Generated by Django 6.0.6 on 2026-06-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='estoque',
            name='nome',
            field=models.CharField(default="", max_length=45, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
