# Generated by Django 6.0.6 on 2026-06-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_funcionario_id_alter_funcionario_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(default='(00) 00000-0000', max_length=15, verbose_name='Telefone'),
        ),
    ]
