# Generated by Django 6.0.6 on 2026-06-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_funcionario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='', max_length=16, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(default='', max_length=16, verbose_name='Telefone'),
        ),
    ]
