# Generated by Django 6.0.6 on 2026-06-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cliente_telefone_alter_funcionario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='categoria',
            field=models.CharField(default='', max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_hora_entrada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e hora da entrada'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_hora_saida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e hora da saída'),
        ),
    ]
