# Generated by Django 6.0.6 on 2026-07-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estoque_categoria_alter_estoque_data_hora_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('lanche', 'Lanche'), ('bebida', 'Bebida')], max_length=45, verbose_name='Categoria'),
        ),
    ]
