# Generated by Django 6.0.6 on 2026-07-02 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('preparando', 'Preparando'), ('concluido', 'Concluído')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_hora_pedido',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e hora do pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacoes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observações'),
        ),
    ]
