# Generated by Django 6.0.6 on 2026-07-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pedido_status_alter_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_hora_pedido',
            field=models.DateTimeField(verbose_name='Data e hora do pedido'),
        ),
    ]
