# Generated by Django 6.0.6 on 2026-07-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_pedido_data_hora_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Endereço'),
        ),
    ]
