# Generated by Django 6.0.6 on 2026-07-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cliente_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cadastro_completo',
            field=models.BooleanField(default=True, verbose_name='Cadastro completo'),
        ),
    ]
