# Generated by Django 6.0.7 on 2026-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_produto_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto_pedido',
            field=models.ImageField(blank=True, null=True, upload_to='novo_pedido/'),
        ),
    ]
