# Generated by Django 6.0.6 on 2026-07-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_produto_foto_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='funcionarios/', verbose_name='Foto de perfil'),
        ),
    ]
